version: 4.2
os: windows
files:
  - source: \
    destination: c:\tmp\
hooks:
  ApplicationStop:
    - location: scripts\stop.bat
      timeout: 300
  BeforeInstall:
    - location: scripts\install_dependencies.bat
      timeout: 300
  AfterInstall:
    - location: scripts\configure.bat
      timeout: 300
  ApplicationStart:
    - location: scripts\start.bat
      timeout: 300
  ValidateService:
    - location: scripts\validate_service.ps1
      timeout: 300
